// Mock data for Hook License System

/**
 * Get a Discord avatar URL from a Discord user ID.
 * Falls back to a default avatar if no ID provided.
 */
export function getDiscordAvatar(discordId: string, discriminator = '0'): string {
  if (!discordId) {
    // Default Discord avatar (grey silhouette)
    const index = parseInt(discriminator) % 5
    return `https://cdn.discordapp.com/embed/avatars/${index}.png`
  }
  // Use Discord's default avatar for the user (no avatar hash known, use generated)
  // For real implementation, you'd store the avatar hash from OAuth
  const index = (BigInt(discordId) >> BigInt(22)) % BigInt(6)
  return `https://cdn.discordapp.com/embed/avatars/${index}.png`
}

export const mockProducts = [
  {
    id: '602',
    name: 'Test Product',
    description: '1',
    productType: 'OTHER',
    otherProductType: 'Test Type',
    productUrl: 'https://builtbybit.com',
    productImageUrl: 'https://placehold.co/600x400/1e293b/94a3b8?text=Test+Product',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-11-16 15:24:23',
    updatedAt: '2024-11-16 15:24:23',
    defaultMaxIps: 4,
    defaultMaxHwids: 3,
  },
  {
    id: '902',
    name: 'MyProduct',
    description: '1',
    productType: 'MINECRAFT_JAVA',
    otherProductType: '',
    productUrl: '',
    productImageUrl: '',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-11-18 01:00:15',
    updatedAt: '2024-11-18 01:00:15',
    defaultMaxIps: 6,
    defaultMaxHwids: 7,
  },
  {
    id: '952',
    name: 'Kasun Actual Test P...',
    description: '',
    productType: 'MINECRAFT_JAVA',
    otherProductType: '',
    productUrl: '',
    productImageUrl: '',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-11-18 01:01:42',
    updatedAt: '2024-11-18 01:01:42',
    defaultMaxIps: 6,
    defaultMaxHwids: 7,
  },
  {
    id: '1052',
    name: 'MyProdPro',
    description: 'test',
    productType: 'OTHER',
    otherProductType: 'ss',
    productUrl: '',
    productImageUrl: '',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-11-18 11:48:45',
    updatedAt: '2024-11-24 21:12:0',
    defaultMaxIps: 5,
    defaultMaxHwids: 5,
  },
  {
    id: '1102',
    name: 'Discord Leaderboar...',
    description: 'Wow Product',
    productType: 'MINECRAFT_JAVA',
    otherProductType: '',
    productUrl: 'https://builtbybit.com/resources/discord-leaderboards.1',
    productImageUrl: 'https://placehold.co/600x400/1e3a5f/60a5fa?text=Discord+Leaderboards',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-12-07 13:56:1',
    updatedAt: '2024-12-07 13:56:1',
    defaultMaxIps: 5,
    defaultMaxHwids: 5,
  },
  {
    id: '1202',
    name: 'Kasun',
    description: 'Hapangama',
    productType: 'MINECRAFT_JAVA',
    otherProductType: '',
    productUrl: '',
    productImageUrl: '',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-12-23 21:45:4',
    updatedAt: '2024-12-23 21:45:4',
    defaultMaxIps: 5,
    defaultMaxHwids: 5,
  },
  {
    id: '1203',
    name: 'testDsx',
    description: 'test',
    productType: 'WEB_APPLICATION',
    otherProductType: '',
    productUrl: '',
    productImageUrl: '',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-12-23 22:17:4',
    updatedAt: '2024-12-23 22:17:4',
    defaultMaxIps: 5,
    defaultMaxHwids: 5,
  },
  {
    id: '1252',
    name: 'SimpleWebsite',
    description: 'A simple Minecraft plugin that allows you to host a website on a MC server!',
    productType: 'MINECRAFT_SERV...',
    otherProductType: '',
    productUrl: 'https://builtbybit.com/resources/simplewebsite.1',
    productImageUrl: 'https://placehold.co/600x400/1a3a2e/4ade80?text=SimpleWebsite',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-12-28 18:33:3',
    updatedAt: '2025-06-07 22:53:',
    defaultMaxIps: 5,
    defaultMaxHwids: 5,
  },
  {
    id: '1302',
    name: 'KasunEmbedTestPr...',
    description: 'myProd',
    productType: 'MINECRAFT_JAVA',
    otherProductType: '',
    productUrl: '',
    productImageUrl: '',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-12-29 15:53:3',
    updatedAt: '2024-12-29 15:53:3',
    defaultMaxIps: 5,
    defaultMaxHwids: 5,
  },
  {
    id: '1352',
    name: 'emtest',
    description: '1',
    productType: 'MINECRAFT_BEDR...',
    otherProductType: '',
    productUrl: '',
    productImageUrl: '',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-12-29 15:56:17',
    updatedAt: '2024-12-29 15:56:17',
    defaultMaxIps: 5,
    defaultMaxHwids: 5,
  },
  {
    id: '1402',
    name: 'test',
    description: 'sss',
    productType: 'WEB_APPLICATION',
    otherProductType: '',
    productUrl: '',
    productImageUrl: '',
    productRole: '',
    productRoleId: '',
    productPurchaseRole: '',
    productPurchaseRoleId: '',
    createdAt: '2024-12-29 15:57:5',
    updatedAt: '2024-12-29 15:57:5',
    defaultMaxIps: 5,
    defaultMaxHwids: 5,
  },
]

export const mockLicenses = [
  {
    id: '1',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-XXR6',
    productId: '602',
    productName: 'Kasun',
    ownerDiscordId: '',
    ownerDiscordUsername: '',
    ownerUsername: '',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-06-27T19:47:36Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '2',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-JQ82',
    productId: '1102',
    productName: 'Discordo',
    ownerDiscordId: '1320619787683889242',
    ownerDiscordUsername: 'Triggered KASUN',
    ownerUsername: 'Triggered KASUN',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-06-27T19:48:49Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '3',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-773B',
    productId: '1052',
    productName: 'Discord Leaderboards',
    ownerDiscordId: '',
    ownerDiscordUsername: 'kaxun',
    ownerUsername: 'kaxun',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'EXPIRED' as const,
    notes: '',
    createdAt: '2025-01-10T10:00:00Z',
    expiresAt: '2025-06-01T00:00:00Z',
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '4',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-71XV',
    productId: '1252',
    productName: 'SimpleWebsite',
    ownerDiscordId: '',
    ownerDiscordUsername: 'kaxun',
    ownerUsername: 'kaxun',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-02-15T08:30:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '5',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-OLHF',
    productId: '1252',
    productName: 'ss',
    ownerDiscordId: '',
    ownerDiscordUsername: 'varkk_',
    ownerUsername: 'varkk_',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-03-01T12:00:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '6',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-JSA8',
    productId: '1102',
    productName: 'Discordo',
    ownerDiscordId: '1320619787683889242',
    ownerDiscordUsername: 'SunLicense',
    ownerUsername: 'SunLicense',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-03-10T15:20:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '7',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-8J7C',
    productId: '1352',
    productName: 'emtest',
    ownerDiscordId: '',
    ownerDiscordUsername: 'itzoverwolf',
    ownerUsername: 'itzoverwolf',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-03-20T09:00:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '8',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-XDFA',
    productId: '1402',
    productName: 'test',
    ownerDiscordId: '',
    ownerDiscordUsername: 'medal.exe',
    ownerUsername: 'medal.exe',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-04-01T11:00:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '9',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-E5IJ',
    productId: '1352',
    productName: 'emtest',
    ownerDiscordId: '',
    ownerDiscordUsername: 'monitr0_',
    ownerUsername: 'monitr0_',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-04-05T14:00:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '10',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-7XSF',
    productId: '902',
    productName: 'role tst null',
    ownerDiscordId: '',
    ownerDiscordUsername: 'monitr0_',
    ownerUsername: 'monitr0_',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-04-10T08:00:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '11',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-MPWJ',
    productId: '1302',
    productName: 'KasunEmbedTestProduct',
    ownerDiscordId: '',
    ownerDiscordUsername: '',
    ownerUsername: '',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-04-15T10:00:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '12',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-H8TH',
    productId: '1202',
    productName: 'RoleIDTest',
    ownerDiscordId: '',
    ownerDiscordUsername: '',
    ownerUsername: '',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-04-20T16:00:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '13',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-RGBJ',
    productId: '1203',
    productName: 'testDsx',
    ownerDiscordId: '',
    ownerDiscordUsername: 'chinezu_1221',
    ownerUsername: 'chinezu_1221',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: '',
    createdAt: '2025-05-01T12:00:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
  {
    id: '14',
    licenseKey: 'AN0U-VT17-L7W5-5299-R7CQ',
    productId: '1102',
    productName: 'Discord Leaderboards Premium',
    ownerDiscordId: '',
    ownerDiscordUsername: 'kaxun',
    ownerUsername: 'kaxun',
    licensePlatform: '',
    licensePlatformUserId: '',
    licenseType: 'PERMANENT',
    status: 'ACTIVE' as const,
    notes: 'Wow Product',
    createdAt: '2025-05-15T09:00:00Z',
    expiresAt: null,
    maxIps: 5,
    maxHwids: 5,
    ips: [],
    hwids: [],
  },
]

export const mockCustomers = [
  {
    id: '1',
    profileImage: 'https://cdn.discordapp.com/embed/avatars/0.png',
    username: '',
    discordUsername: 'Triggered KASUN',
    discordId: '754054589690544250',
    builtByBitUserId: '',
    builtByBitUsername: '',
    firstName: '',
    lastName: '',
    email: '',
    notes: '',
    status: 'ACTIVE',
    licenseCount: 1,
    totalRequests: 0,
    createdAt: '2024-11-16T15:24:23Z',
  },
  {
    id: '2',
    profileImage: 'https://cdn.discordapp.com/embed/avatars/1.png',
    username: '',
    discordUsername: 'kaxun',
    discordId: '754054589690544250',
    builtByBitUserId: '',
    builtByBitUsername: '',
    firstName: 'kaxun',
    lastName: '',
    email: '',
    notes: '',
    status: 'ACTIVE',
    licenseCount: 3,
    totalRequests: 23,
    createdAt: '2024-10-20T10:15:00Z',
  },
  {
    id: '3',
    profileImage: 'https://ui-avatars.com/api/?name=TM&background=7c3aed&color=fff&size=100',
    username: 'thickman',
    discordUsername: 'varkk_',
    discordId: '',
    builtByBitUserId: '',
    builtByBitUsername: '',
    firstName: '',
    lastName: '',
    email: '',
    notes: '',
    status: 'ACTIVE',
    licenseCount: 1,
    totalRequests: 0,
    createdAt: '2024-12-01T10:00:00Z',
  },
  {
    id: '4',
    profileImage: 'https://ui-avatars.com/api/?name=SL&background=f59e0b&color=fff&size=100',
    username: '',
    discordUsername: 'SunLicense',
    discordId: '',
    builtByBitUserId: '',
    builtByBitUsername: '',
    firstName: '',
    lastName: '',
    email: '',
    notes: '',
    status: 'ACTIVE',
    licenseCount: 1,
    totalRequests: 0,
    createdAt: '2024-12-15T12:00:00Z',
  },
  {
    id: '5',
    profileImage: 'https://ui-avatars.com/api/?name=IW&background=10b981&color=fff&size=100',
    username: '',
    discordUsername: 'itzoverwolf',
    discordId: '',
    builtByBitUserId: '',
    builtByBitUsername: '',
    firstName: '',
    lastName: '',
    email: '',
    notes: '',
    status: 'ACTIVE',
    licenseCount: 1,
    totalRequests: 0,
    createdAt: '2025-01-05T09:00:00Z',
  },
  {
    id: '6',
    profileImage: 'https://ui-avatars.com/api/?name=ME&background=64748b&color=fff&size=100',
    username: 'medal.exe',
    discordUsername: 'medal.exe',
    discordId: '',
    builtByBitUserId: '',
    builtByBitUsername: '',
    firstName: '',
    lastName: '',
    email: '',
    notes: '',
    status: 'ACTIVE',
    licenseCount: 1,
    totalRequests: 0,
    createdAt: '2025-02-01T14:00:00Z',
  },
  {
    id: '7',
    profileImage: 'https://ui-avatars.com/api/?name=M0&background=1d4ed8&color=fff&size=100',
    username: 'monitr0_',
    discordUsername: 'monitr0_',
    discordId: '',
    builtByBitUserId: '',
    builtByBitUsername: '',
    firstName: '',
    lastName: '',
    email: '',
    notes: '',
    status: 'ACTIVE',
    licenseCount: 1,
    totalRequests: 0,
    createdAt: '2025-02-10T11:00:00Z',
  },
  {
    id: '8',
    profileImage: 'https://ui-avatars.com/api/?name=CZ&background=111827&color=fff&size=100',
    username: 'chinezu_1221',
    discordUsername: 'chinezu_1221',
    discordId: '',
    builtByBitUserId: '477048',
    builtByBitUsername: '',
    firstName: '',
    lastName: '',
    email: '',
    notes: '',
    status: 'ACTIVE',
    licenseCount: 1,
    totalRequests: 0,
    createdAt: '2025-03-01T08:00:00Z',
  },
]

export const mockRequests = [
  {
    id: '1',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-T0Z5',
    productName: 'Product not found',
    productVersion: '1.0.0',
    ipAddress: '0:0:0:0:0:0:0:1',
    hwid: 'unique-hardware-id3',
    macAddress: '00:1A:2B:3C:4D:5E',
    osVersion: '10',
    operatingSystem: 'Windows',
    osArchitecture: 'x64',
    javaVersion: '17',
    requestType: 'Valid',
    responseType: 'Blocked',
    status: 'Invalid License' as const,
    requestDate: '2025-06-22T17:44:09.534Z',
  },
  {
    id: '2',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-T0Z5',
    productName: 'SimpleWebsite',
    productVersion: '1.0.0',
    ipAddress: '0:0:0:0:0:0:0:1',
    hwid: 'unique-hardware-id3',
    macAddress: '00:1A:2B:3C:4D:5E',
    osVersion: '10',
    operatingSystem: 'Windows',
    osArchitecture: 'x64',
    javaVersion: '17',
    requestType: 'Valid',
    responseType: 'Blocked',
    status: 'HWID blacklisted' as const,
    requestDate: '2025-06-22T17:44:46.915Z',
  },
  {
    id: '3',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-T0Z5',
    productName: 'SimpleWebsite',
    productVersion: '1.0.0',
    ipAddress: '0:0:0:0:0:0:0:1',
    hwid: 'unique-hardware-id4',
    macAddress: '00:1A:2B:3C:4D:5E',
    osVersion: '10',
    operatingSystem: 'Windows',
    osArchitecture: 'x64',
    javaVersion: '17',
    requestType: 'Valid',
    responseType: 'Valid',
    status: 'Successful' as const,
    requestDate: '2025-06-22T17:44:54.692Z',
  },
  {
    id: '4',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-T0Z5',
    productName: 'SimpleWebsite',
    productVersion: '1.0.0',
    ipAddress: '0:0:0:0:0:0:0:1',
    hwid: 'unique-hardware-id4',
    macAddress: '00:1A:2B:3C:4D:5F',
    osVersion: '10',
    operatingSystem: 'Windows',
    osArchitecture: 'x64',
    javaVersion: '17',
    requestType: 'Valid',
    responseType: 'Valid',
    status: 'Successful' as const,
    requestDate: '2025-06-22T17:45:10.37Z',
  },
  {
    id: '5',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-T0Z5',
    productName: 'SimpleWebsite',
    productVersion: '1.0.0',
    ipAddress: '0:0:0:0:0:0:0:1',
    hwid: 'unique-hardware-id4',
    macAddress: '00:1A:2B:3C:4D:5F',
    osVersion: '10',
    operatingSystem: 'Windows',
    osArchitecture: 'x64',
    javaVersion: '17',
    requestType: 'Valid',
    responseType: 'Valid',
    status: 'Successful' as const,
    requestDate: '2025-06-22T17:46:51.094Z',
  },
  {
    id: '6',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-T0Z5',
    productName: 'SimpleWebsite',
    productVersion: '1.0.0',
    ipAddress: '0:0:0:0:0:0:0:1',
    hwid: 'unique-hardware-id4',
    macAddress: '00:1A:2B:3C:4D:5F',
    osVersion: '10',
    operatingSystem: 'Windows',
    osArchitecture: 'x64',
    javaVersion: '17',
    requestType: 'Valid',
    responseType: 'Valid',
    status: 'Successful' as const,
    requestDate: '2025-06-22T17:57:20.067Z',
  },
  {
    id: '7',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-T0Z5',
    productName: 'SimpleWebsite',
    productVersion: '1.0.0',
    ipAddress: '0:0:0:0:0:0:0:1',
    hwid: 'unique-hardware-id4',
    macAddress: '00:1A:2B:3C:4D:5F',
    osVersion: '10',
    operatingSystem: 'Windows',
    osArchitecture: 'x64',
    javaVersion: '17',
    requestType: 'Valid',
    responseType: 'Valid',
    status: 'Successful' as const,
    requestDate: '2025-06-22T17:57:43.848Z',
  },
  {
    id: '8',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-T0Z5',
    productName: 'SimpleWebsite',
    productVersion: '1.0.0',
    ipAddress: '0:0:0:0:0:0:0:1',
    hwid: 'unique-hardware-id4',
    macAddress: '00:1A:2B:3C:4D:5F',
    osVersion: '10',
    operatingSystem: 'Windows',
    osArchitecture: 'x64',
    javaVersion: '17',
    requestType: 'Valid',
    responseType: 'Valid',
    status: 'Successful' as const,
    requestDate: '2025-06-22T18:02:43.902Z',
  },
  {
    id: '9',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-T0Z5',
    productName: 'SimpleWebsite',
    productVersion: '1.0.0',
    ipAddress: '0:0:0:0:0:0:0:1',
    hwid: 'unique-hardware-id3',
    macAddress: '00:1A:2B:3C:4D:5E',
    osVersion: '10',
    operatingSystem: 'Windows',
    osArchitecture: 'x64',
    javaVersion: '17',
    requestType: 'Valid',
    responseType: 'Blocked',
    status: 'HWID blacklisted' as const,
    requestDate: '2025-06-22T22:57:24.917Z',
  },
  {
    id: '10',
    licenseKey: 'XXXX-XXXX-XXXX-XXXX-T0Z5',
    productName: 'SimpleWebsite',
    productVersion: '1.0.0',
    ipAddress: '0:0:0:0:0:0:0:1',
    hwid: 'unique-hardware-id3',
    macAddress: '00:1A:2B:3C:4D:5E',
    osVersion: '10',
    operatingSystem: 'Windows',
    osArchitecture: 'x64',
    javaVersion: '17',
    requestType: 'Valid',
    responseType: 'Blocked',
    status: 'HWID blacklisted' as const,
    requestDate: '2025-06-22T22:57:33.644Z',
  },
]

export const mockBlacklist = [
  {
    id: '1',
    licenseDataType: 'HWID',
    data: 'unique-hardware-id3',
    isForAllProducts: true,
    productId: '',
    reason: 'x',
    createdAt: '2025-02-13T13:11:53Z',
    updatedAt: '2025-02-13T13:11:53Z',
  },
]

export const mockApiTokens = [
  {
    id: '1',
    name: 'license validation token',
    token: 'C7w95iQLgICT3Vavnn4ezZnYRt2jb1lWlv7Yn7Nlc1U',
    intents: ['LICENSE VALIDATE'],
    createdAt: '2025-06-29T17:28:55.454851Z',
  },
  {
    id: '2',
    name: 'testone',
    token: 'cUF2w-im0GxV7l7wz9ikw9F9MRcjQfTHZTaecBtfgMQ',
    intents: ['LICENSE VALIDATE', 'LICENSES READ', 'LICENSES READ WRITE', 'BLACKLISTS READ', 'CUSTOMERS READ', 'ALL READ'],
    createdAt: '2025-06-29T17:43:43.229633Z',
  },
  {
    id: '3',
    name: 'ALL',
    token: 'Hvxaz6zvDwLgJu-pz0Wn5zTij4r08F4dGN4hgmLB9Uw',
    intents: ['ALL READ WRITE'],
    createdAt: '2025-06-29T18:08:45.062265Z',
  },
]

export const mockStats = {
  totalProducts: 28,
  totalRequests: 71,
  totalLicenses: 14,
  systemStatus: 'Operational',
}
